repos:
  - repo: https://github.com/psf/black
    rev: 24.2.0
    hooks:
      - id: black
        language_version: python3.10
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.3.2
    hooks:
      - id: ruff
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
      - id: trailing-whitespace      # Trims invisible spaces at the end of lines
      - id: end-of-file-fixer        # Ensures files end with a single blank line
      - id: check-yaml               # Validates your YAML syntax
      - id: check-added-large-files  # Prevents accidentally committing giant CSVs!
