version: '3.8'

services:
  dev-env:
    build: .
    # Connect your local folder inside the container!
    volumes:
      - ../..:/workspace
    # keep the container running in the background so you can enter and exit it whenever you want
    command: tail -f /dev/null
